####################################################################
# SpringBoot配置文件名称固定，application.properties或者application.yml
###################################################################


#### Profile配置，通过指定application-{profile}.yml, 切换激活相应环境 ####
spring:
  profiles:
#    active: dev
#    active: uat
    active: prod


  #### FreeMarker ####
#  freemarker:
#    suffix: .ftl
#    content-type: text/html
#    charset: utf-8
#    template-loader-path: classpath:/freemarker-page/


  #### Thymeleaf ####
  thymeleaf:
    prefix: classpath:/thymeleaf-page/
    cache: false





#### Logger的输出模式，级别，以及输出到指定文件 ####
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    level: debug
#  file:
#    path: "."
#    name: "springboot.log" #输出到当前目录




