####################################################################
# SpringBoot配置文件名称固定，application.properties或者application.yml
###################################################################


server:
  port: 8081
