####################################################################
# SpringBoot配置文件名称固定，application.properties或者application.yml
###################################################################


#### Profile配置，通过指定application-{profile}.yml, 切换激活相应环境 ####
spring:
  profiles:
#    active: dev
#    active: uat
    active: prod


  #### FreeMarker ####
#  freemarker:
#    suffix: .ftl
#    content-type: text/html
#    charset: utf-8
#    template-loader-path: classpath:/freemarker-page/


  #### Thymeleaf ####
  thymeleaf:
    prefix: classpath:/thymeleaf-page/
    cache: false



  #### JSP ####
  mvc:
    view:
      prefix: classpath:/jsp/
      suffix: .jsp







  #### HikariCP 数据源 ####
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/james?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: jamesjh1984
    schemaUsername: james
    hikari:
      pool-name: James_HikariCP
      minimum-idle: 20
      maximum-pool-size: 100
      idle-timeout: 600000
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 30000






#### c3p0数据源 ####
c3p0:
  driverClass: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/james?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  user: root
  password: jamesjh1984
  #配置最小连接数
  minPoolSize: 2
  #配置最大连接数
  maxPoolSize: 10
  #最大空闲时间
  maxIdleTime: 1800000
  #当连接池中的连接耗尽的时候c3p0一次同时获取的连接数,每次增加3个连接
  acquireIncrement: 3
  #最大sql语句
  maxStatements: 1000
  #初始化连接池数
  initialPoolSize: 3
  idleConnectionTestPeriod: 30
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false












#### Logger的输出模式，级别，以及输出到指定文件 ####
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
#    level: debug
#  file:
#    path: "."
#    name: "springboot.log" #输出到当前目录






#### Mybatis ####
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml
  type-aliases-package: com.jin.springboot.entity
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰命名




#### Pagehelper分页 ####
pagehelper:
  helper-dialect: mysql







